### ISSUE TITLE
Add better logging.

### ISSUE THREAD

**Issue by Nocturnal42** [letsRobot/letsrobot#12]
The controller should be updated to use the python logging module. There should be two targets, console output and log file. The log rotation function should also be used to limit the size of the log files.

This will require touching every .py file, to assign appropriate log levels to every output. I'd be happy for someone else to do this, but it should probably be me, as I am the most familiar with all the output and their level of severity. 

Note: Checking cross compatibility between the python 2 + 3 variant should be done before implementation.

**Comment by skeetermcbee** [comment]
[Python 2 Logging Library](https://docs.python.org/2/library/logging.html)

[Python 3 Logging Library](https://docs.python.org/3/library/logging.html)

**Comment by Nocturnal42** [comment]
I believe it is possible to register an exception handler to catch all unhandled exceptions. Seems like it would have a good idea to do that, in order to log all unhandled exceptions.
