### ISSUE TITLE
Moderator list

### ISSUE THREAD

**Issue by Nocturnal42** [letsRobot/letsrobot#16]
At current the moderator list only lists local mods, should probably expand this to global mods as well. This would allow them access to default moderator level chat commands.

**Comment by jillytot** [comment]
I didn't see this ticket before, but i suggest global mods be put in a separate bucket. Robocasters choose who get to moderate their channel and who has access to that power, but they don't choose global mods. Global modes should only be concerned with enforcing site wide rules, and not channel specific rules. A robocaster needs to make a specific choice to allow global mods access to the robot and channel level moderation.

**Comment by jillytot** [comment]
I'm suggesting that Robocasters should need to take an extra step to give all global mods access to their robot commands.

**Comment by Nocturnal42** [comment]
There is a configuration option in the misc section of the conf file to enable / disable this feature.
