### ISSUE TITLE
Make the startup tts message configurable.

### ISSUE THREAD

**Issue by Nocturnal42** [letsRobot/letsrobot#26]
At its simplest, this is just adding a field to the config file and reading that for the startup / wakeup message. I would like to go a little further, and make it something the modified tts handlers can actually change on their own.

Had a request to make it report the IP address on startup, which is why I am thinking about this.

**Comment by bmorrison4** [comment]
started with commit c3e6b9b

**Comment by bmorrison4** [comment]
Complete.
