### ISSUE TITLE
TTS Volume does not affect USB speakers

### ISSUE THREAD

**Issue by skeetermcbee** [letsRobot/letsrobot#3]

**Comment by Nocturnal42** [comment]
Have you tried setting the TTS volume in the letsrobot.conf file? It should be hardware independent.

**Comment by Nocturnal42** [comment]
It may also be worth adding a chat command handler to allow robocasters to adjust tts volume on the fly.

**Comment by reltham** [comment]
This one was based on the existing runmyrobot code that doesn't seem to work for some speakers.  It was a card I had made on the kanban board that got converted to an issue.  I think we can probably close this, and if testing identifies a fail case then make a new issue.

**Comment by skeetermcbee** [comment]
Closing. Can reopen if needed.
