### ISSUE TITLE
Adafruit_PWM_Servo_Driver

### ISSUE THREAD

**Issue by onlybrezel** [letsRobot/letsrobot#33]
**Is your feature request related to a problem? Please describe.**
Yes, when i uncomment the "from Adafruit_PWM_Servo_Driver import PWM" it wants the Adafruit_PWM_Servo_Driver.py, which dunno exist

**Describe the solution you'd like**
Move Adafruit_PWM_Servo_Driver.py and Adafruit_I2C.py to new repo

**Describe alternatives you've considered**
?, I moved Adafruit_PWM_Servo_Driver.py and Adafruit_I2C.py by myself into hardware folder

**Additional context**

**Comment by Nocturnal42** [comment]
You should not really be editing the hardware modules directly. 

The adafruit libraries are seperate libraries and do not belong in the repo. The readme.md links instructions for correct installation of them.
